const users = [
    {
        guid: "T6mRDY4ueUMSmU_WqbRDU",
        username: "administrator",
        password: "devpoint",
        email: "QuintionTang@gmail.com",
        truename: "Quintion Tang",
        gender: "female",
        avatar: "assets/images/avatars/administrator.jpg",
    },
    {
        guid: "-Z4_h19BB9yEiYZe_qblx",
        password: "12345678",
        username: "hballard",
        email: "hballard@gmail.com",
        truename: "Harper Ballard",
        gender: "female",
        status: 1,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "SR1_xq3rUW1HYUenf_mEH",
        password: "12345678",
        username: "sguzman",
        email: "sguzman@gmail.com",
        truename: "Stevens Guzman",
        gender: "male",
        status: 3,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "-fEsdeFsIInjWxCTPiTsC",
        password: "12345678",
        username: "jrowe",
        email: "jrowe@gmail.com",
        truename: "Jefferson Rowe",
        gender: "male",
        status: 2,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "8zL7IsWispiVa6aDgJE0A",
        password: "12345678",
        username: "frobbins",
        email: "frobbins@gmail.com",
        truename: "Frank Robbins",
        gender: "female",
        status: 1,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "IsRulXvqQLIq2EFRtuBM3",
        password: "12345678",
        username: "plowe",
        email: "plowe@gmail.com",
        truename: "Pearlie Lowe",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "XBMk48gByQ3qJZq9CVAWL",
        password: "12345678",
        username: "nmorales",
        email: "nmorales@gmail.com",
        truename: "Nora Morales",
        gender: "male",
        status: 3,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "ta4mO08Nw0f8ww6Cz6aYR",
        password: "12345678",
        username: "hengland",
        email: "hengland@gmail.com",
        truename: "Howe England",
        gender: "female",
        status: 1,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "3-1LQ0dzkPYBwZeiyCBZR",
        password: "12345678",
        username: "gblair",
        email: "gblair@gmail.com",
        truename: "Goodman Blair",
        gender: "male",
        status: 2,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "7nZONaT2CJs7K1mGCDg-Z",
        password: "12345678",
        username: "bmolina",
        email: "bmolina@gmail.com",
        truename: "Burks Molina",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "Wp2Wh4pHVFkMYZipB-Oc5",
        password: "12345678",
        username: "lmarquez",
        email: "lmarquez@gmail.com",
        truename: "Lidia Marquez",
        gender: "female",
        status: 1,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "SRoD8NnHVOhcXXWa2Wazu",
        password: "12345678",
        username: "jfleming",
        email: "jfleming@gmail.com",
        truename: "Jolene Fleming",
        gender: "male",
        status: 2,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "Q-DraVNTKgPtI9tOOONUJ",
        password: "12345678",
        username: "bboyle",
        email: "bboyle@gmail.com",
        truename: "Bryan Boyle",
        gender: "male",
        status: 2,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "GoJS8T31nzGafCdZe1dYL",
        password: "12345678",
        username: "mwhitaker",
        email: "mwhitaker@gmail.com",
        truename: "Mccarty Whitaker",
        gender: "female",
        status: 2,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "d3c8lfw8TGS-xoUKW3LiI",
        password: "12345678",
        username: "mhoover",
        email: "mhoover@gmail.com",
        truename: "Matthews Hoover",
        gender: "male",
        status: 3,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "LhEIjc_1GUO2yR4gfmQ_3",
        password: "12345678",
        username: "bwarner",
        email: "bwarner@gmail.com",
        truename: "Barrett Warner",
        gender: "male",
        status: 2,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "gzJWv4fD6gfJyiOKxZjQD",
        password: "12345678",
        username: "gdelgado",
        email: "gdelgado@gmail.com",
        truename: "Grace Delgado",
        gender: "female",
        status: 1,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "AvDwAkD2M9ouadu_ELUGf",
        password: "12345678",
        username: "vspencer",
        email: "vspencer@gmail.com",
        truename: "Vicki Spencer",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "jXItS2rWwtzKAJQwec2F-",
        password: "12345678",
        username: "mcamacho",
        email: "mcamacho@gmail.com",
        truename: "Marla Camacho",
        gender: "male",
        status: 3,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "VHqlk5a_mW5JPXK7i3EOW",
        password: "12345678",
        username: "cturner",
        email: "cturner@gmail.com",
        truename: "Chambers Turner",
        gender: "female",
        status: 3,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "Obh6gLCc6e4UIE0z91PSZ",
        password: "12345678",
        username: "rvelasquez",
        email: "rvelasquez@gmail.com",
        truename: "Ruthie Velasquez",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "y346yKnyjG_dYGoN5iyDa",
        password: "12345678",
        username: "snguyen",
        email: "snguyen@gmail.com",
        truename: "Silvia Nguyen",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "XG-2jG-rPoLRE7JJtinHw",
        password: "12345678",
        username: "tcooper",
        email: "tcooper@gmail.com",
        truename: "Terry Cooper",
        gender: "female",
        status: 2,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "37Tj7GjtjxqkH4Ct5SjKa",
        password: "12345678",
        username: "brogers",
        email: "brogers@gmail.com",
        truename: "Bianca Rogers",
        gender: "male",
        status: 2,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "AKFv1jZs1tZPKdGBgAq54",
        password: "12345678",
        username: "cmacdonald",
        email: "cmacdonald@gmail.com",
        truename: "Cole Macdonald",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "l6abM_2UHzBd4xeBPVevS",
        password: "12345678",
        username: "chodge",
        email: "chodge@gmail.com",
        truename: "Coleen Hodge",
        gender: "female",
        status: 2,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "_6CEazltzY0g_DuzVM6Uu",
        password: "12345678",
        username: "rwilliam",
        email: "rwilliam@gmail.com",
        truename: "Rowland William",
        gender: "male",
        status: 3,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "hd0iJGiJu_LnUVo5cvh40",
        password: "12345678",
        username: "cbaxter",
        email: "cbaxter@gmail.com",
        truename: "Coffey Baxter",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "DzZTxNrUjxuYlh7IU0urZ",
        password: "12345678",
        username: "rcabrera",
        email: "rcabrera@gmail.com",
        truename: "Ruiz Cabrera",
        gender: "female",
        status: 1,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "YGVWj-bTgjkxeGPcQEsK3",
        password: "12345678",
        username: "ilindsay",
        email: "ilindsay@gmail.com",
        truename: "Ingrid Lindsay",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "oDrxJNELMD5HcsTRZbRe1",
        password: "12345678",
        username: "ccastro",
        email: "ccastro@gmail.com",
        truename: "Charlene Castro",
        gender: "male",
        status: 2,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "3Ye0QHhTEf6w7VNSoG7SB",
        password: "12345678",
        username: "lbeck",
        email: "lbeck@gmail.com",
        truename: "Leach Beck",
        gender: "female",
        status: 1,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "xB_MnzXmnBPFiDKTUfIRp",
        password: "12345678",
        username: "wgalloway",
        email: "wgalloway@gmail.com",
        truename: "Wilkerson Galloway",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "IAu_6PArLZLnha3SeIf6D",
        password: "12345678",
        username: "lleblanc",
        email: "lleblanc@gmail.com",
        truename: "Louella Leblanc",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "TcQ0G_aublYzbCqpZ3Kg-",
        password: "12345678",
        username: "fcochran",
        email: "fcochran@gmail.com",
        truename: "Fitzpatrick Cochran",
        gender: "female",
        status: 2,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "AoGalVbeQ0NOX477bWV3g",
        password: "12345678",
        username: "mstokes",
        email: "mstokes@gmail.com",
        truename: "Mercer Stokes",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "-jUjzx7PubHmx24ycppcs",
        password: "12345678",
        username: "lbarber",
        email: "lbarber@gmail.com",
        truename: "Lily Barber",
        gender: "male",
        status: 2,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "oYaAE-UBcblT7aObDxe-v",
        password: "12345678",
        username: "mbenjamin",
        email: "mbenjamin@gmail.com",
        truename: "Morse Benjamin",
        gender: "female",
        status: 2,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "ximaW3EC6TAM30ymojDKh",
        password: "12345678",
        username: "ngay",
        email: "ngay@gmail.com",
        truename: "Nixon Gay",
        gender: "male",
        status: 2,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "73ee1Qg8aeQ483T5hMVcU",
        password: "12345678",
        username: "shenderson",
        email: "shenderson@gmail.com",
        truename: "Sweeney Henderson",
        gender: "male",
        status: 2,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "GFpk-MZbjSGsKZrHo9uC3",
        password: "12345678",
        username: "etanner",
        email: "etanner@gmail.com",
        truename: "Edna Tanner",
        gender: "female",
        status: 3,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "Q7iZtzqho8B1og2jV3UnA",
        password: "12345678",
        username: "kstrickland",
        email: "kstrickland@gmail.com",
        truename: "Kaye Strickland",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "gMdO3F_HE-kgRgoL8KeXF",
        password: "12345678",
        username: "tcruz",
        email: "tcruz@gmail.com",
        truename: "Taylor Cruz",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "dAwIau1ABXEtab6SSR_8a",
        password: "12345678",
        username: "mlivingston",
        email: "mlivingston@gmail.com",
        truename: "Mullins Livingston",
        gender: "female",
        status: 2,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "AbuwYBNWrNhmgzR82pvAS",
        password: "12345678",
        username: "frichard",
        email: "frichard@gmail.com",
        truename: "Fitzgerald Richard",
        gender: "male",
        status: 2,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "PxI8jAR3KjcQepHlLgAAF",
        password: "12345678",
        username: "cduffy",
        email: "cduffy@gmail.com",
        truename: "Cain Duffy",
        gender: "male",
        status: 1,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "oA8DP_RLc-KCaBXvkYSjT",
        password: "12345678",
        username: "fgrimes",
        email: "fgrimes@gmail.com",
        truename: "Frazier Grimes",
        gender: "female",
        status: 3,
        avatar: "assets/images/avatars/female.jpg",
    },
    {
        guid: "N4AztAS4_b43LG5U18Oft",
        password: "12345678",
        username: "wreed",
        email: "wreed@gmail.com",
        truename: "Ward Reed",
        gender: "male",
        status: 3,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "1cAJ9pd-y59VEPvqmzbOa",
        password: "12345678",
        username: "lmontoya",
        email: "lmontoya@gmail.com",
        truename: "Latonya Montoya",
        gender: "male",
        status: 3,
        avatar: "assets/images/avatars/male.jpg",
    },
    {
        guid: "sj-ExBgflY2pnI-CxL8Y-",
        password: "12345678",
        username: "sgilmore",
        email: "sgilmore@gmail.com",
        truename: "Small Gilmore",
        gender: "female",
        status: 3,
        avatar: "assets/images/avatars/female.jpg",
    },
];
/**
 * status:1:Shipped;2:Pending;3:Sent;4:Cancelled
 */
const orders = [
    {
        id: "kNF5Y7q7WBpt62GxFNoEZ",
        customer: "Marva Fry",
        amount: 1488.56,
        date: "2020-21-02",
        status: 2,
    },
    {
        id: "0VCm2epONtgE38fLfmjgH",
        customer: "Sabrina Coffey",
        amount: 1570.62,
        date: "2020-04-02",
        status: 2,
    },
    {
        id: "GiPwqHSLJd_mGkYlx9RsL",
        customer: "Reed Heath",
        amount: 1537.02,
        date: "2020-07-02",
        status: 2,
    },
    {
        id: "VcvKJHPY82PxGnfEVU1mt",
        customer: "Krystal Shaffer",
        amount: 1327.09,
        date: "2020-20-02",
        status: 2,
    },
    {
        id: "xC9dbVGEC-HgbSMHA3DPP",
        customer: "Romero Dawson",
        amount: 454.52,
        date: "2020-06-02",
        status: 3,
    },
    {
        id: "Q0i_K7LJ4ByZqNCR9OQVh",
        customer: "Bell Preston",
        amount: 921.77,
        date: "2020-08-02",
        status: 1,
    },
    {
        id: "e1_dNULGoz6adI4apyk5N",
        customer: "Vickie Warner",
        amount: 1966.72,
        date: "2020-19-02",
        status: 3,
    },
    {
        id: "8hidaDCGb_3tnVquTVIWJ",
        customer: "Patrica Cervantes",
        amount: 1302,
        date: "2020-03-02",
        status: 3,
    },
    {
        id: "5C81hifJ6qxMb76Fh9UTY",
        customer: "Reva Hays",
        amount: 1522.56,
        date: "2020-20-02",
        status: 2,
    },
    {
        id: "iTjUtQK3Auq5Hs2t4qut8",
        customer: "Golden Myers",
        amount: 87.74,
        date: "2020-04-02",
        status: 3,
    },
    {
        id: "LwHBUAzfi_QZYl8yS8ogJ",
        customer: "Patti Riddle",
        amount: 886.11,
        date: "2020-04-02",
        status: 2,
    },
    {
        id: "wXtyGvr21yg0nekQTraaE",
        customer: "David Richmond",
        amount: 889.47,
        date: "2020-07-02",
        status: 2,
    },
    {
        id: "X0kirFTxUHAhf422CIxLv",
        customer: "Ferrell Burton",
        amount: 91.76,
        date: "2020-05-02",
        status: 1,
    },
    {
        id: "SVLgSGX5_xs4scoLEV1nT",
        customer: "Simmons Ashley",
        amount: 216.47,
        date: "2020-04-02",
        status: 1,
    },
    {
        id: "LiTFxe8TqDuQ3JUrE9LCs",
        customer: "Rebekah Bishop",
        amount: 310.63,
        date: "2020-04-02",
        status: 1,
    },
    {
        id: "yG_qg0iZTpaicxlIcjjI7",
        customer: "Letha Guthrie",
        amount: 984.62,
        date: "2020-05-02",
        status: 2,
    },
    {
        id: "WLgorkl3u5tPHeoK675Ik",
        customer: "Hartman Hancock",
        amount: 1838.95,
        date: "2020-20-02",
        status: 3,
    },
    {
        id: "lpNmINVr78NxJrVRKLiw3",
        customer: "Guzman Dodson",
        amount: 622.44,
        date: "2020-22-02",
        status: 2,
    },
    {
        id: "uuQpi1SDA1KHsrWZt8-EY",
        customer: "Blanche Bright",
        amount: 163.7,
        date: "2020-05-02",
        status: 1,
    },
    {
        id: "3ha54kMWEYdGmO6mc8ii6",
        customer: "Edith Buchanan",
        amount: 604.18,
        date: "2020-04-02",
        status: 1,
    },
    {
        id: "mIxB9KWXQtGlElghLdK-b",
        customer: "French Walton",
        amount: 767.1,
        date: "2020-24-02",
        status: 1,
    },
    {
        id: "LVDEDG-Wbvo42IkrCgMfX",
        customer: "Fletcher Kirk",
        amount: 1130.99,
        date: "2020-05-02",
        status: 1,
    },
    {
        id: "wetDbxk5s9KAiD0WfQMLb",
        customer: "Mccarthy Dillon",
        amount: 1854.89,
        date: "2020-19-02",
        status: 3,
    },
    {
        id: "MitDaaLlbJTMFWF5cb1yB",
        customer: "Lamb Hunt",
        amount: 312.02,
        date: "2020-02-02",
        status: 2,
    },
    {
        id: "TZff5Afr46OCjr8quNrdf",
        customer: "Hamilton Valentine",
        amount: 322.21,
        date: "2020-23-02",
        status: 4,
    },
    {
        id: "U7UfN5tGTH-S8l61mSJkS",
        customer: "Fowler Baker",
        amount: 1634.26,
        date: "2020-20-02",
        status: 2,
    },
    {
        id: "uq9fPp6-Pq7uwAYZt1gYA",
        customer: "Therese Olsen",
        amount: 1290.85,
        date: "2020-07-02",
        status: 2,
    },
    {
        id: "3S0CnT3AKJ6EgNNlPgusd",
        customer: "Carmela Kirkland",
        amount: 829.45,
        date: "2020-03-02",
        status: 3,
    },
    {
        id: "TXfAmRQeX1z_gSjWQHSLy",
        customer: "Adriana Alford",
        amount: 1280.66,
        date: "2020-08-02",
        status: 2,
    },
    {
        id: "tpsuIU6RY0dIrWInRp4US",
        customer: "Marisa Meyer",
        amount: 1250.89,
        date: "2020-09-02",
        status: 2,
    },
    {
        id: "DX-SX8D2G7tMV-vgkccIh",
        customer: "Middleton Salas",
        amount: 1702.22,
        date: "2020-21-02",
        status: 4,
    },
    {
        id: "I0Cp5Bot_n1RqwxP7DDP3",
        customer: "Effie Zimmerman",
        amount: 1466.22,
        date: "2020-20-02",
        status: 1,
    },
    {
        id: "IDJaAqPCG_KfovHqCCFPa",
        customer: "Morin Lowe",
        amount: 1503.41,
        date: "2020-05-02",
        status: 2,
    },
    {
        id: "fSxoM0KuZOo-Q712hJyPT",
        customer: "Rodriguez Morgan",
        amount: 412.1,
        date: "2020-14-02",
        status: 3,
    },
    {
        id: "AOz9aH28kvnuNO-dk8DPy",
        customer: "Hooper Murray",
        amount: 382.36,
        date: "2020-04-02",
        status: 1,
    },
    {
        id: "oDzZrYoztMT3zHsAX0pTl",
        customer: "Angelia Woodard",
        amount: 1964.4,
        date: "2020-10-02",
        status: 4,
    },
    {
        id: "PA1jhapywVGcLQAyMNj2o",
        customer: "Eva Fleming",
        amount: 957.81,
        date: "2020-18-02",
        status: 3,
    },
    {
        id: "B_btprQrQqBu-g6kZ6kZU",
        customer: "Helena Bryant",
        amount: 279.66,
        date: "2020-08-02",
        status: 2,
    },
    {
        id: "fLChAKB7Lzpd8Dfdv2EMw",
        customer: "Ruby Prince",
        amount: 1828.48,
        date: "2020-22-02",
        status: 3,
    },
    {
        id: "wkQmB0n5Pbf5fRw5-L8hE",
        customer: "Goff Ayala",
        amount: 1843.72,
        date: "2020-23-02",
        status: 1,
    },
    {
        id: "8X7fBEc7YtWDGz9DpR2LD",
        customer: "Johnston Ramirez",
        amount: 1395.37,
        date: "2020-04-02",
        status: 4,
    },
    {
        id: "I3vktbBkmolW3a2b96ixc",
        customer: "King Huffman",
        amount: 510.35,
        date: "2020-07-02",
        status: 1,
    },
    {
        id: "UuoPok9wgeQMa2WGDrG-3",
        customer: "Hutchinson Rhodes",
        amount: 1264.34,
        date: "2020-20-02",
        status: 3,
    },
    {
        id: "Z2fW9JxN20CGSokQL4Ssk",
        customer: "Adele Dunn",
        amount: 260.48,
        date: "2020-08-02",
        status: 2,
    },
    {
        id: "wodmPCHTL7ePFx1O3ui2x",
        customer: "Fuller Brady",
        amount: 1656.03,
        date: "2020-14-02",
        status: 4,
    },
    {
        id: "lZ8d99PY4Gxoe48qRFgrd",
        customer: "Kristen Vincent",
        amount: 1745.58,
        date: "2020-21-02",
        status: 1,
    },
    {
        id: "lUMTqKKrT0tVMZtVf5s9q",
        customer: "Burt Wolf",
        amount: 1641.1,
        date: "2020-19-02",
        status: 2,
    },
    {
        id: "80mEGMftHbqRgvp328ePs",
        customer: "Bridgette Nielsen",
        amount: 787.58,
        date: "2020-21-02",
        status: 4,
    },
    {
        id: "K2kt6nGtJSY5KjFINsU3S",
        customer: "Morgan Gonzales",
        amount: 1800.88,
        date: "2020-10-02",
        status: 1,
    },
    {
        id: "5Q2jVxWJE8wD-xGy7FnvD",
        customer: "Lindsey Johnston",
        amount: 596.87,
        date: "2020-17-02",
        status: 4,
    },
];

const products = [
    {
        id: "fgr22nCTKhTl0fhA6YHRG",
        thumb: "/assets/images/products/ps4.jpg",
        title: "PlayStation 4 1TB (Jet Black)",
        instock: 52,
        price: 480,
        sales: 123,
        views: 3432,
        status: 1,
    },
    {
        id: "TmBHEG7TchZC1eOY5osyi",
        thumb: "/assets/images/products/nike-1.jpg",
        title: "Nike Men Black Liteforce III Sneakers",
        instock: 34,
        price: 57.55,
        sales: 222,
        views: 7231,
        status: 1,
    },
    {
        id: "tUdJDYVeDjlUXywX1liVo",
        thumb: "/assets/images/products/headphones.jpg",
        title: "Wireless headphones",
        instock: 0,
        price: 235.55,
        sales: 43,
        views: 3572,
        status: 2,
    },
    {
        id: "nj2GVBji1gsPjnOM438oP",
        thumb: "/assets/images/products/backpack.jpg",
        title: "HERO ATHLETES BAG",
        instock: 11,
        price: 160,
        sales: 38,
        views: 3111,
        status: 3,
    },
    {
        id: "5sQ0KzCsdC2fD9penMD-o",
        thumb: "/assets/images/products/chair-1.jpg",
        title: "POÄNG",
        instock: 70,
        price: 159,
        sales: 34,
        views: 5489,
        status: 1,
    },
    {
        id: "Bu3C6ka7yesMwN0SGDoUE",
        thumb: "/assets/images/products/iwatch.jpg",
        title: "Apple iWatch (black)",
        instock: 9,
        price: 399,
        sales: 22,
        views: 4123,
        status: 1,
    },
    {
        id: "vnwYBpN_1mwPXA7SRWGM-",
        thumb: "/assets/images/products/sunglasses.jpg",
        title: "WALKING 400 BLUE CAT3",
        instock: 20,
        price: 20.55,
        sales: 24,
        views: 12231,
        status: 1,
    },
    {
        id: "yMRTXGZuW4QCz5gd4TqtK",
        thumb: "/assets/images/products/adidas.jpg",
        title: "Adidas Sneakers Originals",
        instock: 53,
        price: 57.55,
        sales: 98,
        views: 2391,
        status: 3,
    },
    {
        id: "fgdqczOW5DF1B9KlbC4hV",
        thumb: "/assets/images/products/s7edge-1.jpg",
        title: "Samsung Galaxy S7 Edge",
        instock: 0,
        price: 1049,
        sales: 128,
        views: 6298,
        status: 2,
    },
    {
        id: "-dtmb_atxjOTQ0Zj8WqzH",
        thumb: "/assets/images/products/ps4.jpg",
        title: "PlayStation 4 1TB (Jet Black)",
        instock: 52,
        price: 480,
        sales: 123,
        views: 3432,
        status: 1,
    },
    {
        id: "UTnmCMt4EJXj3TEvoGZ89",
        thumb: "/assets/images/products/nike-1.jpg",
        title: "Nike Men Black Liteforce III Sneakers",
        instock: 34,
        price: 57.55,
        sales: 222,
        views: 7231,
        status: 1,
    },
    {
        id: "WaA9i4pW7oaOMclrbtS4p",
        thumb: "/assets/images/products/headphones.jpg",
        title: "Wireless headphones",
        instock: 41,
        price: 235.55,
        sales: 43,
        views: 3572,
        status: 1,
    },
    {
        id: "IT0wNlA736m99m4hObPsu",
        thumb: "/assets/images/products/backpack.jpg",
        title: "HERO ATHLETES BAG",
        instock: 11,
        price: 160,
        sales: 38,
        views: 3111,
        status: 3,
    },
    {
        id: "p7baY33bFX5eqnZ2iFxqf",
        thumb: "/assets/images/products/chair-1.jpg",
        title: "POÄNG",
        instock: 70,
        price: 159,
        sales: 34,
        views: 5489,
        status: 3,
    },
    {
        id: "UExE1VjSFHk4p7_lF8b8T",
        thumb: "/assets/images/products/iwatch.jpg",
        title: "Apple iWatch (black)",
        instock: 9,
        price: 399,
        sales: 22,
        views: 4123,
        status: 1,
    },
    {
        id: "Iy5FbzWxhHGQW0yTtZUV-",
        thumb: "/assets/images/products/sunglasses.jpg",
        title: "WALKING 400 BLUE CAT3",
        instock: 20,
        price: 20.55,
        sales: 24,
        views: 12231,
        status: 1,
    },
    {
        id: "aHRftwan_GHh4uSVLTwwy",
        thumb: "/assets/images/products/adidas.jpg",
        title: "Adidas Sneakers Originals",
        instock: 53,
        price: 57.55,
        sales: 98,
        views: 2391,
        status: 1,
    },
    {
        id: "hbRBd852ofOzEASTA-wZM",
        thumb: "/assets/images/products/s7edge-1.jpg",
        title: "Samsung Galaxy S7 Edge",
        instock: 32,
        price: 1049,
        sales: 128,
        views: 6298,
        status: 1,
    },
    {
        id: "ToaVmAxcKpaC5LNklN3BC",
        thumb: "/assets/images/products/ps4.jpg",
        title: "PlayStation 4 1TB (Jet Black)",
        instock: 0,
        price: 480,
        sales: 123,
        views: 3432,
        status: 2,
    },
    {
        id: "06gtjTQuFaoFpSWI-nXdv",
        thumb: "/assets/images/products/nike-1.jpg",
        title: "Nike Men Black Liteforce III Sneakers",
        instock: 34,
        price: 57.55,
        sales: 222,
        views: 7231,
        status: 1,
    },
    {
        id: "ig9I2GevjQh_YUbm8iOTR",
        thumb: "/assets/images/products/headphones.jpg",
        title: "Wireless headphones",
        instock: 41,
        price: 235.55,
        sales: 43,
        views: 3572,
        status: 1,
    },
    {
        id: "H3QMtGXhFyfSBG_mVDpiW",
        thumb: "/assets/images/products/backpack.jpg",
        title: "HERO ATHLETES BAG",
        instock: 11,
        price: 160,
        sales: 38,
        views: 3111,
        status: 1,
    },
    {
        id: "laO1JePDa3Jj5qzg4oR-5",
        thumb: "/assets/images/products/chair-1.jpg",
        title: "POÄNG",
        instock: 70,
        price: 159,
        sales: 34,
        views: 5489,
        status: 1,
    },
    {
        id: "COdi9BARjh8MLjFO5aBxD",
        thumb: "/assets/images/products/iwatch.jpg",
        title: "Apple iWatch (black)",
        instock: 9,
        price: 399,
        sales: 22,
        views: 4123,
        status: 1,
    },
    {
        id: "_kVcA3LXFozbn21HLf-eZ",
        thumb: "/assets/images/products/sunglasses.jpg",
        title: "WALKING 400 BLUE CAT3",
        instock: 20,
        price: 20.55,
        sales: 24,
        views: 12231,
        status: 3,
    },
    {
        id: "AwylYbGNpDkq8SOzRPPK-",
        thumb: "/assets/images/products/adidas.jpg",
        title: "Adidas Sneakers Originals",
        instock: 53,
        price: 57.55,
        sales: 98,
        views: 2391,
        status: 1,
    },
    {
        id: "9Z26Mb3Df3CW3dSgZb5t1",
        thumb: "/assets/images/products/s7edge-1.jpg",
        title: "Samsung Galaxy S7 Edge",
        instock: 32,
        price: 1049,
        sales: 128,
        views: 6298,
        status: 1,
    },
    {
        id: "gZddHPwIhR3JDd9s6Z0Xh",
        thumb: "/assets/images/products/iwatch.jpg",
        title: "Apple iWatch (black)",
        instock: 9,
        price: 399,
        sales: 22,
        views: 4123,
        status: 1,
    },
    {
        id: "otk1_xWuDDHi8Id_hTpp3",
        thumb: "/assets/images/products/sunglasses.jpg",
        title: "WALKING 400 BLUE CAT3",
        instock: 20,
        price: 20.55,
        sales: 24,
        views: 12231,
        status: 1,
    },
    {
        id: "onYjeMSjUcrqUK8pxOpcO",
        thumb: "/assets/images/products/adidas.jpg",
        title: "Adidas Sneakers Originals",
        instock: 0,
        price: 57.55,
        sales: 98,
        views: 2391,
        status: 2,
    },
    {
        id: "KSd_Edg8He1oUfZ7__rCF",
        thumb: "/assets/images/products/s7edge-1.jpg",
        title: "Samsung Galaxy S7 Edge",
        instock: 32,
        price: 1049,
        sales: 128,
        views: 6298,
        status: 1,
    },
    {
        id: "tpo5oSvIDda6pGUy_bJhM",
        thumb: "/assets/images/products/ps4.jpg",
        title: "PlayStation 4 1TB (Jet Black)",
        instock: 52,
        price: 480,
        sales: 123,
        views: 3432,
        status: 1,
    },
    {
        id: "hM3zIXuBQz8QP28FMwvHL",
        thumb: "/assets/images/products/nike-1.jpg",
        title: "Nike Men Black Liteforce III Sneakers",
        instock: 34,
        price: 57.55,
        sales: 222,
        views: 7231,
        status: 1,
    },
    {
        id: "wPGBNZzVFLbf9YRd4qAeX",
        thumb: "/assets/images/products/headphones.jpg",
        title: "Wireless headphones",
        instock: 0,
        price: 235.55,
        sales: 43,
        views: 3572,
        status: 2,
    },
    {
        id: "T688rJ61_znIRZsKpCtFa",
        thumb: "/assets/images/products/backpack.jpg",
        title: "HERO ATHLETES BAG",
        instock: 11,
        price: 160,
        sales: 38,
        views: 3111,
        status: 1,
    },
    {
        id: "VgiyNgMxfxffaqYfY-XlU",
        thumb: "/assets/images/products/chair-1.jpg",
        title: "POÄNG",
        instock: 70,
        price: 159,
        sales: 34,
        views: 5489,
        status: 1,
    },
    {
        id: "4rFaq-IDbjYOE81UqLHzn",
        thumb: "/assets/images/products/iwatch.jpg",
        title: "Apple iWatch (black)",
        instock: 9,
        price: 399,
        sales: 22,
        views: 4123,
        status: 1,
    },
];
export { users, products };
